# Generated by Django 3.2.8 on 2021-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0012_auto_20211021_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnmpesaonline',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
